server:
  port: 8011
  servlet:
    context-path: /
spring:
  application:
    name: simulate
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML