spring:
  datasource:
    url: jdbc:mysql://rm-8vb01ra5w94yq5n48.mysql.zhangbei.rds.aliyuncs.com:3306/simulate?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: shop
    password: Shop666999
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
host:
  b2c: http://pay.szyhb.cn/b2c
  local: http://pay.szyhb.cn:8011